name: FHIR API Test Suite

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch: 

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run:
          curl -o-  "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Run FHIR API tests
        run: |
          postman collection run "postman/collections/FHIR Project" \
            --env-var base_url=https://hapi.fhir.org/baseR4
